server:
  port: 8888

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bej
    username: volka
    password: novski
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            user-name-attribute: id
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
        registration:
          kakao:
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8888/login/oauth2/code/kakao
            client-id: dbe236d60fa6568ffcb50fa04263cdc9
            client-secret: TfNxYfuH1zOD8a5S7eqUcCTWPZ0lbuua
            client-authentication-method: POST
            scope: profile_nickname,account_email



logging:
  level:
    org:
      springframework: info
      springframework.security: trace
    com:
      project: debug